### PR TITLE
Switch to OkHttp.

### PR DESCRIPTION
**Pull request by SimonVT**
Use OkHttp instead of HttpUrlConnection.

This also moves many responsibilities from aXMLRPC to OkHttp:
- Cookies
- Follow redirects
- SSL
- Proxy
- Authentication

### CODE REVIEW

**Comment by gturri** [comment]
Thanks you for this pull request. It indeed sounds like a good idea to rely on a library rather than reinventing the wheel.
Given the amount of changed code, it will take some time before I can study the pros and cons in depth.

After a first quick look, a first question though: some public methods seem gone (at least `getCookies` and `clearCookies`), while other are changed (eg: `getURL` which returned a `URL`, is now `getHttpUrl` and returns an `HttpUrl`). Would it be possible to avoid removing current public methods, and to avoid exposing the implementation (ie: to avoid returning objects from the `okhttp3` namespace)?

**Comment by SimonVT** [comment]
This is more for a v2 release so the API can be changed.

The advantage of moving to OkHttp is that aXMLRPC doesn't have to have any code related to authentication, cookies, proxies, etc. By letting the user provide their own `OkHttpClient`, this can all be managed using the OkHttp API.
All the removed methods are implementation details of how OkHttp implements these features, and should in my opinion not be part `XMLRPCClient`.

Regarding `getHttpUrl`, it could be changed to return a `String`. There's not much reason to do this tho - if you decide to commit to OkHttp, its classes are already exposed through the constructor.

**Comment by gturri** [comment]
Thanks for the clarification.

Before I look more in depth, I have another concern: axmlrpc is currently available in [debian](https://packages.debian.org/testing/java/libaxmlrpc-java)  (and [Ubuntu](http://packages.ubuntu.com/xenial/java/libaxmlrpc-java)) repositories. So CLI tools (eg: [dokujclient](https://packages.debian.org/testing/java/dokujclient)) which use it can be installed out of the box with `apt-get install`.

AFAICS, `OkHttp` isn't available in debian, and it would itself require `OkIo` to be added.
Are you aware of any plan to have those packages in debian?

**Comment by SimonVT** [comment]
Ah, I wasn't aware of that use-case.

I don't use debian/ubuntu, so I don't have any experience with their repositories. I'm from the Android(/Java) world where dependencies are available in Maven Central.
I haven't seen any request for adding OkHttp to the debian/ubuntu repositories, but I doubt it's something they'd be interested in maintaining.

If this is not the route you want to go, you could take a look at e.g. Gson and just expose a few `toXml` and `fromXml` methods (and use `String`, `Reader`, `Appendable`, etc). This would let the user use whatever HTTP client they want. You also wouldn't have to keep updating the library as the preferred http library changes (previously everyone used Apaches `HttpClient` on Android, then `HttpUrlConnection`, and these days OkHttp is the de facto standard).
If you like the convenience, you could add some `XMLRPCHttpUrlConnection` and `XMLRPCOkHttp` classes on top that does roughly what `XMLRPCClient` does today.

Btw, don't feel any obligation to merge this. I have a local fork I use, but I figured I'd offer you the opportunity to merge these changes if you wanted.

**Pull request closed without merging**
